### ISSUE TITLE
Error on script load

### ISSUE THREAD

**Issue by ianwijma** [GreenComfyTea/OBS-Stats-on-Stream#3]
Hey,

I was checking out the script you've written, and on load I was getting the following error: 

```
[OBS-Stats-on-Stream.lua] Error running file: ...udio/data/scripts/OBS-Stats-on-Stream-main//ljsocket.lua:837: table index is nil
```

**Comment by ianwijma** [comment]
I do need to add that I'm on Linux, and us the flatpack version of obs-studio

**Comment by GreenComfyTea** [comment]
This error is related to socket library I use, not to my script: https://github.com/CapsAdmin/luajitsocket/issues/2.

**Comment by GreenComfyTea** [comment]
Implemented the suggested fix in 6b21fb5db9f569676fd5fef6f75fd1a1dccd10de. Let me know if that works so I can close the issue.

**Comment by ianwijma** [comment]
First changed it to: 

```lua
    errno = {}
    errno.EAGAIN = 11,
    errno.EWOULDBLOCK = errno.EAGAIN
    errno.ENOTSOCK = 88
    errno.ECONNRESET = 104
    errno.EINPROGRESS = 115    
```

Which still caused an error: 
```
[OBS-Stats-on-Stream.lua] Error running file: error loading module 'ljsocket' from file '/path/to/OBS-Stats-on-Stream-main//ljsocket.lua':
	/path/to/OBS-Stats-on-Stream-main//ljsocket.lua:691: unexpected symbol near '='
```

Looks like the following worked:
```lua
    errno = {
        EAGAIN = 11,
        ENOTSOCK = 88,
        ECONNRESET = 104,
        EINPROGRESS = 115,
    }
    errno.EWOULDBLOCK = errno.EAGAIN 
```

I don't know LUA enough so my bad if I copied something wrong. Just wanted to make sure its known something was broken.

**Comment by GreenComfyTea** [comment]
If anybody reads this - no need to edit anything manually, it has been fixed here. Thanks for your feedback, ianwijma! Closing the issue.
