### ISSUE TITLE
Displaying current streaming state if live, reconnecting or stopped

### ISSUE THREAD

**Issue by TheB1gG** [GreenComfyTea/OBS-Stats-on-Stream#7]
Hello,
thanks for this great script. Would it be possible to also show the current state of the stream? It would be very interesting for me to show this to have this info for my recordings.

Thank you

**Comment by GreenComfyTea** [comment]
The only states I can track are live and not-live. Those are determined by user input - you pressing start streaming and stop streaming button. Any other reasons for stream to stop being live and/or reconnect are related to OBS being in an error state (in which case the status is unpredictable) or related to twitch/youtube/etc server status (which is out of scope of this script).

If you still want me to add LIVE/OFFLINE status, let me know.

**Comment by TheB1gG** [comment]
Hi,
thanks for the reply. That is sad, I thought that you would be able to show the reconnecting like the GUI does. But if this is not exposed to your script there can't be done much I guess. The Live/OFFLINE status is maybe for somebody else usefull, so it can't hurt to be added I guess.
Anyways thanks for the help and have a great day.

**Comment by GreenComfyTea** [comment]
My apologies, I did manage to get reconnection status. Implemented in c8f2f75.
