### ISSUE TITLE
Question Regarding Command Use

### ISSUE THREAD

**Issue by GitHubQueenn** [GreenComfyTea/OBS-Stats-on-Stream#8]
Hi, can you please tell me what I'd need to add to the OBS-STATS file so that only specified users can use the commands and where I'd need to place it in the code?

Thank you.

**Comment by GreenComfyTea** [comment]
![image](https://user-images.githubusercontent.com/30152047/151669328-0dfd44cd-de25-4966-944d-98c984396ff5.png)

**Comment by GitHubQueenn** [comment]
> ![image](https://user-images.githubusercontent.com/30152047/151669328-0dfd44cd-de25-4966-944d-98c984396ff5.png)

When I reload the screipt after adding those changes to the file, I get an error on OBS that says:
`[OBS-Stats-on-Stream.lua] Error loading file: C:/Users/user/folder/OBS-Stats-on-Stream.lua:328: 'end' expected (to close 'for' at line 220) near 'until'`

**Comment by GitHubQueenn** [comment]
> ![image](https://user-images.githubusercontent.com/30152047/151669328-0dfd44cd-de25-4966-944d-98c984396ff5.png)

Ok, so I added 2 test users that I want to be able to use the command and a 3rd test account that does *not* have the permission, however the 3rd test account is still able to execute the commands.

**Comment by GreenComfyTea** [comment]
try replacing `do break end` with `return`

**Comment by GitHubQueenn** [comment]
> try replacing `do break end` with `return`

Perfect, it's working how it should. Thanks a ton!

**Comment by GreenComfyTea** [comment]
No problem!
