### ISSUE TITLE
Question: Possible to start script on OBS Startup?

### ISSUE THREAD

**Issue by GitHubQueenn** [GreenComfyTea/OBS-Stats-on-Stream#9]
So, I noticed if I start OBS like normal and stream, my OBS commands don't work. I have to manually go to Tools>Scripts>Right-click the script>Reload each time and then it will work. Any way to fix that?

**Comment by GreenComfyTea** [comment]
I will look into that.
If possible send me your logs, please?

**Comment by GitHubQueenn** [comment]
> 

My OBS logs?

**Comment by GreenComfyTea** [comment]
Script logs. 
![image](https://user-images.githubusercontent.com/30152047/152038538-c48a1058-dd21-4dce-a637-82f53aa37536.png)
